spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: microsercicio-plazoleta


server:
  port: 8081


